version: 2
jobs:
  build:
    docker:    #Dockerイメージの設定
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: test_sample01
          - DB_USERNAME: root

      - image: circleci/mysql:5.7-ram    #データベースの設定
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: test_sample01

    steps:
      - checkout

      - run: sudo apt update       #パッケージの情報を最新のものに変更
      - run: sudo docker-php-ext-install pdo_mysql    #MySQL用のPDO拡張をインストール

      - restore_cache:    # キャッシュを復帰
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:    #キャッシュを保存
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: echo "APP_KEY=" > .env.testing    
      - run: php artisan key:generate    #APP_KEYだけを書いた.env.testingを作成してgenerateする
      - run: php artisan migrate
      - run: ./vendor/bin/phpunit    #テスト実行
