version: 2
jobs:
  docker:
    - image: circleci/php:7.1-node-browsers

  steps:
    - checkout

    - run:
        name: Greeting
        command: echo Hello, world.

    - run:
        name: Print the Current Time
        command: date